version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: npm install
      - run: npm build
  test:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: npm install
      - run: echo "Muhahahaha"
workflows:
  node-tests:
    jobs:
      - build
      - test
