version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: npm install
      - run: echo "Muhahahaha"
workflows:
  node-tests:
    jobs:
      - build
      - test
